global:
  scrape_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

- job_name: prometheus
  static_configs:
    - targets: ['host.docker.internal:9090']

- job_name: rocky
  static_configs:
    - targets: ['rocky:9100']

- job_name: 'prom_middleware'
  scrape_interval: 5s
  static_configs:
    - targets: ['host.docker.internal:9091']

- job_name: 'github_exporter'
  scrape_interval: 1h
  static_configs:
    - targets: ['host.docker.internal:9171']

