global:
  scrape_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:

- job_name: prometheus
  static_configs:
    - targets: ['localhost:9090']

- job_name: mac
  static_configs:
    - targets: ['host.docker.internal:9100']

- job_name: rocky
  static_configs:
    - targets: ['rocky:9100']