# config file version
apiVersion: 1

# List of contact points to import or update
contactPoints:
  # <int> organization ID, default = 1
  - orgId: 1
    # <string, required> name of the contact point
    name: grafana-default-email
    receivers:
      # <string, required> unique identifier for the receiver
      - uid: grafana-default-email
        # <string, required> type of the receiver
        type: email
        settings:
          # <string, required>
          addresses: some@email.example
          # <bool>
          singleEmail: false
          # <string>
          message: my optional message to include
          # <string>
          subject: |
            {{ template "default.title" . }}
